import { PortfolioItem } from '@/types/project';

// =============================================================================
// ENTERPRISE PROTOTYPES
// =============================================================================
export const enterprisePrototypes: PortfolioItem[] = [
    {
        slug: 'netflixcontent',
        title: 'Global Content Demand Forecaster (GCDF)',
        tagline: 'Predictive intelligence for what to greenlight, renew, or license next.',
        company: 'Netflix',
        category: 'enterprise',
        year: '2025',
        role: 'Product Management & Systems Design',
        tags: ['Streaming', 'Forecasting', 'Content Strategy', 'OpenAI'],
        proof: 'I can translate ambiguous content strategy decisions into an internal forecasting product with clear inputs and decision outputs.',
        problem: 'Content planning is high-stakes but demand signals are fragmented across regions, genres, and time windows. Teams struggle to compare titles fairly and quantify slate risk.',
        impact: [
            'Faster decision cycles by consolidating demand signals into a single forecasting cockpit.',
            'More consistent greenlight/renewal decisions through comparable title-level forecasts.',
            'Better portfolio management by surfacing slate concentration risk.',
        ],
        description: [
            'GCDF is a concept product for Netflix content strategy teams to forecast demand and evaluate slate decisions.',
            'It provides title-level predictions, scenario planning, and portfolio risk views.',
            'Built with Next.js 16, React 19, and OpenAI for intelligent demand modeling.',
        ],
        liveUrl: 'https://netflixcontent.com',
        repoUrl: 'https://github.com/lelandsequel/netflixcontent',
        status: 'concept',
    },
    {
        slug: 'amazonfulfill',
        title: 'Fulfillment Forecast & Routing Optimizer (FFRO)',
        tagline: 'AI-assisted forecasting and routing recommendations for fulfillment operations.',
        company: 'Amazon',
        category: 'enterprise',
        year: '2025',
        role: 'Product Management & Systems Design',
        tags: ['Supply Chain', 'Forecasting', 'Optimization', 'OpenAI'],
        proof: 'I can model fulfillment constraints and translate them into a decision cockpit with measurable tradeoffs.',
        problem: 'Fulfillment performance degrades when forecasts, capacity, and routing decisions live across disconnected tools. Teams react late to demand shifts and miss service-level targets.',
        impact: [
            'Improved forecast-to-plan cycle time by consolidating demand, capacity, and routing.',
            'Reduced late-stage volume rework by surfacing constraint violations earlier.',
            '50% reduction in manual scenario testing time for regional planners.',
        ],
        description: [
            'FFRO simulates expert logistics planner logic to visualize network health and optimize routing.',
            'It assigns Service Level Risk Scores (0-100) and recommends specific routing changes.',
            'Planners can run rapid what-if scenarios and export actionable routing shifts.',
        ],
        liveUrl: 'https://amazonfulfill.com',
        repoUrl: 'https://github.com/lelandsequel/amazonfulfill',
        status: 'concept',
    },
    {
        slug: 'chevronlift',
        title: 'ChevronLift — FracFlow Command Center',
        tagline: 'Real-time completions & logistics cockpit for multi-well frac operations.',
        company: 'Chevron',
        category: 'enterprise',
        year: '2025',
        role: 'Product Management & Systems Architecture',
        tags: ['Energy Ops', 'Completions', 'Scheduling', 'Logistics'],
        proof: 'I can model operational constraints and ship an execution cockpit that recomputes plans under disruption.',
        problem: 'Frac operations break between systems: sand, water, crews, equipment are coordinated across spreadsheets and texts. When constraints shift, teams re-plan manually.',
        impact: [
            'Reduced non-productive time by surfacing constraint conflicts early.',
            'Faster re-planning during disruptions via scenario recompute.',
            'Improved cross-team alignment with one shared operational plan.',
        ],
        description: [
            'ChevronLift is a concept command center for completions teams managing frac spreads.',
            'It centralizes schedule, constraints, vendor logistics, and cost burn.',
            'Teams can detect drift and recompute plans fast when reality changes.',
        ],
        liveUrl: 'https://chevronlift.vercel.app',
        repoUrl: 'https://github.com/lelandsequel/chevron-lift',
        status: 'in-progress',
    },
    {
        slug: 'gasflow',
        title: 'GasFlow — Pipeline Scheduling Automation',
        tagline: 'Never miss a nomination deadline. Automate FERC pipeline gas scheduling.',
        company: 'Energy Trading',
        category: 'enterprise',
        year: '2026',
        role: 'Product Management & Systems Architecture',
        tags: ['Energy Trading', 'Pipeline Ops', 'Scheduling', 'NAESB'],
        proof: 'I can model regulatory timing constraints and ship a scheduling tool that prevents costly deadline misses.',
        problem: 'Gas traders must nominate volumes on FERC pipelines by specific deadlines. Miss a deadline = cannot move gas = real money lost. Coordination happens across multiple pipeline portals and spreadsheets.',
        impact: [
            'Eliminated missed nomination deadlines through consolidated tracking.',
            'Reduced manual data entry by 70% with auto-routing suggestions.',
            'Single pane of glass for all nominations and trade-to-physical matching.',
        ],
        description: [
            'GasFlow is a pipeline scheduling automation tool for gas traders and schedulers.',
            'It tracks NAESB nomination cycles (Timely, Evening, Intraday) with countdown timers and alerts.',
            'Features include trade-to-physical matching, auto-routing suggestions, and nomination workflow management.',
        ],
        liveUrl: 'https://gasflow.vercel.app',
        repoUrl: 'https://github.com/lelandsequel/gas-scheduler',
        status: 'in-progress',
    },
    {
        slug: 'jpmhomelending',
        title: 'MortgageOps — Home Lending Portfolio Control Tower',
        tagline: 'Portfolio-level visibility and execution control for home lending operations.',
        company: 'JPMorgan Chase',
        category: 'enterprise',
        year: '2025',
        role: 'Product Management & Systems Architecture',
        tags: ['Portfolio Ops', 'Fintech', 'Exceptions', 'Risk Management'],
        proof: 'I can design portfolio-level control systems that surface risk early and enable intervention.',
        problem: 'Home Lending portfolios span dozens of programs and vendors. Status lives across Jira, spreadsheets, and vendor portals. Issues surface after SLAs breach.',
        impact: [
            'Earlier identification of SLA breach risk.',
            'Reduced last-minute escalations through proactive intervention.',
            'Fewer surprises in executive reviews.',
        ],
        description: [
            'MortgageOps is a concept control tower for Home Lending portfolio leadership.',
            'It provides single operational truth across origination, underwriting, closing, and funding.',
            'Focuses on intervention, not reporting: surfaces what needs attention and who should act.',
        ],
        liveUrl: 'https://jpmhomelending.com',
        status: 'concept',
    },
    {
        slug: 'via-vendor-intelligence',
        title: 'Vendor Intelligence & Automation (VIA)',
        tagline: 'Vendor onboarding, risk scoring, and contract visibility with automation.',
        company: 'Enterprise',
        category: 'enterprise',
        year: '2025',
        role: 'Product Management & Systems Architecture',
        tags: ['Vendor Risk', 'Compliance', 'Automation', 'Procurement'],
        proof: 'I can build procurement workflows that standardize vendor evaluation while maintaining auditability.',
        problem: 'Heavy reliance on external vendors with manual, fragmented onboarding and limited risk visibility.',
        impact: [
            '30-50% reduction in onboarding time through standardized scoring.',
            'Improved compliance visibility via centralized vendor profiles.',
            'Faster, more consistent vendor decisioning.',
        ],
        description: [
            'VIA is a concept platform for procurement, risk, and compliance teams.',
            'It centralizes vendor discovery, AI-powered risk scoring, and contract intelligence.',
            'Built for enterprises with complex vendor ecosystems needing speed without sacrificing governance.',
        ],
        status: 'concept',
    },
    {
        slug: 'los-migration',
        title: 'LOS Migration Platform',
        tagline: 'Real-time KPI tracking, team skill assessments, and incident management for loan origination system migrations.',
        company: 'Chase',
        category: 'enterprise',
        year: '2025',
        role: 'Product Management & Systems Architecture',
        tags: ['Fintech', 'Migration', 'KPIs', 'Team Development', 'Incident Management'],
        proof: 'I can design operational control systems that track migration health, team readiness, and system incidents in real time.',
        problem: 'LOS migrations involve complex coordination across teams, integrations, and skill development. Status lives across disconnected tools, making it hard to identify risks early.',
        impact: [
            'Real-time visibility into migration KPIs and health trends.',
            'Proactive identification of team skill gaps through assessments.',
            'Faster incident resolution with centralized tracking and root cause analysis.',
            'Improved team readiness through structured development plans.',
        ],
        description: [
            'LOS Migration Platform is a comprehensive management tool for loan origination system migrations.',
            'Features real-time dashboards, integration monitoring, incident management, and team skill assessments.',
            'Built with Next.js 15, TypeScript, Supabase, and shadcn/ui for a modern, accessible experience.',
        ],
        liveUrl: 'https://los-migration.vercel.app',
        repoUrl: 'https://github.com/lelandsequel/los-migration',
        status: 'live',
    },
];

// =============================================================================
// SOLUTIONS ARCHITECTURE
// =============================================================================
export const solutionsArchitecture: PortfolioItem[] = [
    {
        slug: 'claude-code-training',
        title: 'Claude Code Training',
        tagline: 'Professional AI development training platform with interactive lessons and exercises.',
        company: 'Jourdan Labs',
        category: 'solutions',
        year: '2026',
        role: 'Full-Stack Development & Product',
        tags: ['AI', 'Training', 'Claude Code', 'Next.js', 'Education'],
        problem: 'Developers need structured training to leverage AI coding assistants effectively. Most resources are scattered tutorials without hands-on practice.',
        impact: [
            'Comprehensive 5-module curriculum from fundamentals to production.',
            '30+ interactive coding exercises with real-world scenarios.',
            'Quizzes and certificate upon completion.',
            'Self-paced learning with progress tracking.',
        ],
        description: [
            'Claude Code Training is a complete professional development platform.',
            'Covers agentic coding, permission models, CI/CD integration, MCP servers, and enterprise deployment.',
            'Built with Next.js, featuring interactive exercises, quizzes, and certificate generation.',
        ],
        liveUrl: 'https://jourdanlabs.com/claudecode',
        status: 'live',
    },
    {
        slug: 'cl-job-match',
        title: 'C&L Job Match',
        tagline: 'AI-powered job matching and resume optimization for executive placement.',
        company: 'C&L',
        category: 'solutions',
        year: '2025',
        role: 'Full-Stack Development & Product',
        tags: ['Recruiting', 'AI', 'LLM', 'Next.js', 'Supabase'],
        problem: 'Executive recruiters spend hours manually matching candidates to roles. The process is inconsistent and doesn\'t scale.',
        impact: [
            'Reduced matching time from hours to minutes with AI-powered scoring.',
            'Consistent evaluation using standardized role family matching.',
            'Automated resume tailoring for specific roles.',
            'Integrated with ATS systems (Greenhouse, Lever, Ashby, Workday).',
        ],
        description: [
            'C&L Job Match uses LLMs to match candidates with open positions.',
            'Ingests jobs from multiple ATS platforms and scores candidates against requirements.',
            'Generates tailored resumes and cover letters optimized for specific positions.',
        ],
        liveUrl: 'https://cljobmatch.com',
        status: 'live',
    },
    {
        slug: 'cl-desk',
        title: 'C&L Desk',
        tagline: 'Lead management and deal tracking for business development.',
        company: 'C&L',
        category: 'solutions',
        year: '2025',
        role: 'Full-Stack Development & Product',
        tags: ['CRM', 'Lead Management', 'Sales Ops', 'Next.js', 'Supabase'],
        problem: 'Lead tracking scattered across spreadsheets and email with no unified pipeline view.',
        impact: [
            'Centralized lead tracking with clear pipeline stages.',
            'Automated follow-up reminders and Slack notifications.',
            'Better visibility into deal progress and conversion.',
        ],
        description: [
            'C&L Desk is the internal CRM for the C&L business development team.',
            'Tracks leads from initial contact through close with integrated deliverable management.',
            'Sends automated notifications via Slack when leads need attention.',
        ],
        status: 'live',
    },
    {
        slug: 'cl-ops-console',
        title: 'C&L Ops Console',
        tagline: 'Operational command center for project delivery and artifact management.',
        company: 'C&L',
        category: 'solutions',
        year: '2026',
        role: 'Full-Stack Development & Product',
        tags: ['Ops', 'Project Management', 'Artifacts', 'Next.js', 'Supabase'],
        problem: 'Project artifacts and delivery status scattered across multiple systems.',
        impact: [
            'Single source of truth for all project artifacts.',
            'Clear visibility into delivery pipeline status.',
            'Streamlined handoffs with claim and assignment workflows.',
        ],
        description: [
            'C&L Ops Console is the operational backbone for managing project delivery.',
            'Tracks runs, artifacts, and events across all client projects.',
            'Team members can claim work, update status, and download artifact bundles.',
        ],
        status: 'live',
    },
    {
        slug: 'tsunami-well-lite',
        title: 'Tsunami Well Lite',
        tagline: 'AI-assisted well data analysis and visualization.',
        company: 'C&L',
        category: 'solutions',
        year: '2025',
        role: 'Full-Stack Development & Product',
        tags: ['Energy', 'Data Analysis', 'AI', 'Visualization', 'React'],
        problem: 'Well data analysis requires manual processing and specialized expertise.',
        impact: [
            'Faster well data analysis with AI assistance.',
            'Accessible insights for non-technical stakeholders.',
            'Standardized visualization of well performance.',
        ],
        description: [
            'Tsunami Well Lite analyzes and visualizes well data.',
            'Users upload well data files and get AI-assisted interpretation.',
            'Dashboard provides clear visualizations for non-technical users.',
        ],
        status: 'live',
    },
    {
        slug: 'los-migration',
        title: 'LOS Migration Platform',
        tagline: 'Real-time KPI tracking, team skill assessments, and incident management for loan origination system migrations.',
        company: 'Chase',
        category: 'solutions',
        year: '2025',
        role: 'Full-Stack Development & Product',
        tags: ['Fintech', 'Migration', 'Next.js', 'Supabase', 'Recharts'],
        proof: 'I can design operational control systems that track migration health, team readiness, and system incidents in real time.',
        problem: 'LOS migrations involve complex coordination across teams, integrations, and skill development. Status lives across disconnected tools, making it hard to identify risks early.',
        impact: [
            'Real-time visibility into migration KPIs and health trends.',
            'Proactive identification of team skill gaps through assessments.',
            'Faster incident resolution with centralized tracking and root cause analysis.',
            'Improved team readiness through structured development plans.',
        ],
        description: [
            'LOS Migration Platform is a comprehensive management tool for loan origination system migrations.',
            'Features real-time dashboards, integration monitoring, incident management, and team skill assessments.',
            'Built with Next.js 15, TypeScript, Supabase, and shadcn/ui for a modern, accessible experience.',
        ],
        liveUrl: 'https://los-migration.vercel.app',
        repoUrl: 'https://github.com/lelandsequel/los-migration',
        status: 'live',
    },
    {
        slug: 'cl-edge',
        title: 'C&L Edge',
        tagline: 'AI-powered trading signals, forecasts, and risk analytics for energy commodities.',
        company: 'C&L',
        category: 'solutions',
        year: '2026',
        role: 'Full-Stack Development & Product',
        tags: ['Energy Trading', 'AI', 'Forecasting', 'Risk Analytics', 'Next.js'],
        problem: 'Energy traders are outgunned by quant desks. Data is scattered across multiple sources, analysis is manual, and signals come too late.',
        impact: [
            'AI-generated trading signals with confidence scores for CL, NG, HO, RB.',
            'Price forecasts at 1-day, 7-day, and 30-day horizons.',
            'Real-time risk analytics including VaR and correlation matrices.',
            'Spread analysis (crack, spark, calendar) surfaced automatically.',
            'News sentiment scoring to filter signal from noise.',
        ],
        description: [
            'C&L Edge is an energy commodities trading intelligence platform.',
            'Provides AI-powered signals, forecasts, risk analytics, and sentiment analysis.',
            'Traders can upload their CSV trade history for custom backtesting and calibration.',
            'Built for traders who want quant-level intelligence without the Goldman price tag.',
        ],
        liveUrl: 'https://cl-intel.com/energy',
        status: 'live',
    },
];

// =============================================================================
// PROPOSAL SITES
// =============================================================================
export const proposalSites: PortfolioItem[] = [
    {
        slug: 'energy-alloys',
        title: 'Energy Alloys',
        tagline: 'B2B materials supplier website with SEO optimization strategy.',
        company: 'Energy Alloys',
        category: 'proposal',
        year: '2025',
        role: 'Strategy, Design & Development',
        tags: ['B2B', 'Manufacturing', 'SEO', 'Next.js', 'pSEO'],
        problem: 'Outdated web presence with poor search visibility and unclear value proposition.',
        impact: [
            'Modern, conversion-focused website design.',
            'Comprehensive SEO strategy targeting high-intent B2B keywords.',
            'Programmatic SEO pages for material + application combinations.',
        ],
        description: [
            'Energy Alloys demonstrates a complete digital transformation for a B2B materials supplier.',
            'Features programmatic SEO pages targeting specific material + industry combinations.',
            'Includes SEO audit, keyword taxonomy, and content strategy deliverables.',
        ],
        liveUrl: 'https://energy-alloys.com',
        status: 'live',
    },
    {
        slug: 'rockspring',
        title: 'Rockspring',
        tagline: 'Texas commercial real estate firm website and SEO strategy.',
        company: 'Rockspring',
        category: 'proposal',
        year: '2025',
        role: 'Strategy, Design & Development',
        tags: ['Real Estate', 'Commercial', 'SEO', 'Texas Triangle'],
        problem: 'Fragmented web presence that doesn\'t reflect market position.',
        impact: [
            'Unified brand presentation across services.',
            'Location-based SEO for Texas Triangle markets.',
            'Clear service differentiation.',
        ],
        description: [
            'Rockspring is a proposal site for a Texas commercial real estate firm.',
            'Separates brokerage, development, and investment services clearly.',
            'Includes location-based SEO pages for Texas markets.',
        ],
        liveUrl: 'https://cl-rockspring.com',
        status: 'live',
    },
    {
        slug: 'ivone-health',
        title: 'IV One Health',
        tagline: 'Healthcare provider website with patient-focused content strategy.',
        company: 'IV One Health',
        category: 'proposal',
        year: '2025',
        role: 'Strategy, Design & Development',
        tags: ['Healthcare', 'Medical', 'SEO', 'Patient Experience'],
        problem: 'Medical practice needs modern web presence with clear service information.',
        impact: [
            'Patient-friendly service descriptions.',
            'Condition and treatment content strategy.',
            'Clear call-to-action for appointments.',
        ],
        description: [
            'IV One Health focuses on patient experience for a healthcare provider.',
            'Features detailed service pages, condition guides, and patient process explanation.',
            'Includes Answer Engine Optimization (AEO) for AI search visibility.',
        ],
        liveUrl: 'https://cl-proposal.com',
        status: 'live',
    },
];

// =============================================================================
// EXPORTS
// =============================================================================
export const allPortfolioItems: PortfolioItem[] = [
    ...enterprisePrototypes,
    ...solutionsArchitecture,
    ...proposalSites,
];

export function getPortfolioItemBySlug(slug: string): PortfolioItem | undefined {
    return allPortfolioItems.find(item => item.slug === slug);
}

export function getPortfolioItemsByCategory(category: PortfolioItem['category']): PortfolioItem[] {
    return allPortfolioItems.filter(item => item.category === category);
}
